apiVersion: v1
kind: Service
metadata:
  name: nlp-service
  namespace: quizgen
  labels:
    app: nlp-service
    app.kubernetes.io/part-of: quizgen-platform
spec:
  selector:
    app: nlp-service
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
