apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: quizgen
  labels:
    app: ollama
    app.kubernetes.io/part-of: quizgen-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi   # Mistral 7B ~4 Go + marge
  storageClassName: standard
