apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: quizgen
  labels:
    app: postgres
    app.kubernetes.io/part-of: quizgen-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate   # PostgreSQL ne supporte pas le rolling update avec volume
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: quizgen
            - name: POSTGRES_USER
              value: quizgen
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quizgen-secrets
                  key: DB_PASS
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "quizgen", "-d", "quizgen"]
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "quizgen", "-d", "quizgen"]
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-db
          configMap:
            name: postgres-init-scripts
